// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Fallback to hardcoded values to prevent white-screen crashes on GitHub Pages
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gsbedjumhddbetvxxthe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_xBbLj5J9cSjozZzxpfisFg_2-OyJErR";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});
